common_args:
  env_name: Pendulum-v1
  max_timesteps: 100000
  eval_freq: 1000
  window_size: 10
  early_stop: false
  h_size: 128
  # norm_obs: True
  # norm_reward: True
PPO:
  actor_lr: 0.0003
  critic_lr: 0.0002
  gae_lambda: 0.95
  update_times: 10
  horizon: 256
  batch_size: 128
  target_kl: 0.05
A2C:
  actor_lr: 0.0003
  critic_lr: 0.0002
  horizon: 256
  batch_size: 128
REINFORCE:
  gamma: 0.99
  lr: 0.0003
