env_name: CartPole-v1 # CliffWalking-v0 # CartPole-v1
alg_name: DoubleDuelingNoisyDQN # DoubleDuelingNoisyDQN
lr: 0.0001
# max_epochs: 1000
# max_episode_steps: 300
report_freq: 10
max_timesteps: 20000
sync_freq: 64
memory_size: 5000
eval_freq: 100
std_init: 0.5
batch_size: 32
# norm_obs: True
# norm_reward: True