alg_name: PPO
env_name: Pendulum-v1 # Pendulum-v1 # HalfCheetah-v5  # CartPole-v1 Pendulum-v1
max_timesteps: 100000
h_size: 128
actor_lr: 0.0003
critic_lr: 0.0002
batch_size: 128 # 256 128 64
horizon: 256 # 2048 256
update_times: 10
norm_obs: True
norm_reward: True
norm_advantage: False # True
target_kl: 0.05 # 0.01
eval_freq: 1000
num_envs: 1