env_name: HalfCheetah-v5 # HalfCheetah-v5  # CartPole-v1
max_timesteps: 1000000
# max_epochs: 1000
h_size: 128
actor_lr: 0.0003
critic_lr: 0.0002
batch_size: 64 # 256 128 64
horizon: 2048 # 2048 256
update_times: 10
norm_obs: True
norm_reward: False
norm_advantage: True
target_kl: 0.05 # 0.01
eval_freq: 1000
num_envs: 1