env_name: HalfCheetah-v5  # CartPole-v1 # Pendulum-v1 # HalfCheetah-v5 
alg_name: SAC
max_timesteps: 1000000
h_size: 256
actor_lr: 0.0003
critic_lr: 0.0003
batch_size: 256
memory_size: 30000
tau: 0.005
# norm_obs: True
expl_steps: 10000
eval_freq: 1000
alpha: 0.15