common_args:
  env_name: CartPole-v1
  train_mode: timestep
  max_timesteps: 20000
  timestep_freq: 100
  report_freq: 100
  window_size: 10
  max_episode_steps: 500
  reward_threshold: 475.0
  early_stop: false
PPO:
  baseline: 0
  actor_lr: 0.05
  critic_lr: 0.005
  entropy_coef: 0.001
  eps_clip: 0.2
  gamma: 0.99
  h_size: 32
  is_gae: true
  lmbda: 0.95
  update_freq: 50
  update_times: 5
REINFORCE:
  baseline: 0
  gamma: 0.99
  h_size: 32
  lr: 0.005
A2C:
  baseline: 0
  gamma: 0.99
  h_size: 32
  lmbda: 0.95
  actor_lr: 0.05
  critic_lr: 0.005